feat(action): action poetry update
moneymeets/action-poetry-update pull request #1
Opened 2024-09-25 14:06 UTC by IamAbbey

Action test

https://github.com/moneymeets/moneymeets-mail-dashboard/actions/runs/11034693570/job/30648868059

PR created

https://github.com/moneymeets/moneymeets-mail-dashboard/pull/105

2024-09-30 11:03 UTC, felix11h requested changes
Looks good! I left a couple of comments, I think this is mostly just clean up that we can still do. The only thing I didn't look at in detail is the pull request logic.

2024-09-30 11:03 UTC, felix11h commented on actions_helper/main.py
> +@click.option("--dry-run", default="false", type=str)
I was surprised that click doesn't have a type or parser for this. I guess you already looked for it as well, I also couldn't find anything in my quick search. Your `parse_bool` utils function is good in this case.

2024-10-01 07:18 UTC, IamAbbey commented on tests/__init__.py
removed

2024-10-01 07:23 UTC, IamAbbey commented on actions_helper/commands/update_dependency.py
> +        f"poetry update {'--dry-run' if dry_run else ''} --no-ansi",
`dry-run` option is useful for local runs while developing for debugging.

2024-10-01 07:28 UTC, IamAbbey commented on actions_helper/commands/update_dependency.py
> +    )
`poetry update` *contains* skipped packages info during `--dry-run`

2024-10-01 07:29 UTC, IamAbbey commented on action.yml
> +    default: ''
keeping it since it is optional

2024-10-01 08:45 UTC, felix11h commented on actions_helper/commands/update_dependency.py
> +    )
Fair enough, but my argument is (see other comment), that we never want to run poetry update in dry run mode. The dry run option to me only makes sense for whether we want to make a pull request, but dependencies should always be updated.

2024-10-01 08:54 UTC, felix11h commented on actions_helper/commands/update_dependency.py
> +def update_package(dry_run: bool) -> str:
```suggestion
def update_dependencies(dry_run: bool) -> str:
```
or at least
```suggestion
def update_packages(dry_run: bool) -> str:
```
?

2024-10-01 08:55 UTC, felix11h commented
Thanks for the updates and fixes, @IamAbbey. From the requirements in MD-7569, I think updating poetry itself is still missing?

2024-10-02 07:23 UTC, felix11h approved these changes
🚀

2024-10-02 07:39 UTC, merged